import os 
from dotenv import load_dotenv


load_dotenv()

# Moduls names
WHATCH_MODULE_NAME = os.getenv("WHATCHDOG_MODULE","WATCHDOG_MODULE")
MAIN_PIPELINE_MODULE_NAME = os.getenv("MAIN_PIPELINE_MODULE","MAIN_PIPELINE_MODULE")
FRAME_STREAM_MODULE_NAME = os.getenv("FRAME_STREAMER_MODULE","FRAME_STREAMER_MODULE")
DETECTOR_MODULE_NAME = os.getenv("DETECTOR_MODULE","DETECTOR_MODULE")
DISSPLAY_MODULE_NAME = os.getenv("DISPLAY_MODULE","DISPLAY_MODULE")
PLAYER_MODULE_NAME = os.getenv("DISPLAY_MODULE","DISPLAY_MODULE")


# Paths
MP4_VIDEO_CONTENT_FOLDER = os.getenv("MP4_VIDEO_CONTENT_FOLDER", "content/videos")
GENERATED_FRAMES_FOLDER = os.getenv("GENERATED_FRAMES_FOLDER", "content/generated_frames")
RESULTS_FRAME_FOLDER = os.getenv("RESULTS_FRAME_FOLDER", "content/results_frames")


# Process setup
FRAME_STREAM_QUEUE_SIZE = os.getenv("FRAME_STREAM_QUEUE_SIZE", 10)
DETECTOR_WORKER_COUNT = os.getenv("DETECTOR_WORKER_COUNT", 1)
DETECTED_FRAMES_QUEUE_SIZE = os.getenv("DETECTED_FRAMES_QUEUE_SIZE", 10)
